/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type {
  Signer,
  AddressLike,
  ContractDeployTransaction,
  ContractRunner,
} from "ethers";
import type { NonPayableOverrides } from "../../common";
import type {
  NFTStorageERC721,
  NFTStorageERC721Interface,
} from "../../contracts/NFTStorageERC721";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_collectionAddress",
        type: "address",
      },
      {
        internalType: "address",
        name: "_owner",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "collectionAddress",
    outputs: [
      {
        internalType: "contract IERC721",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "depositToken",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "",
        type: "bytes",
      },
    ],
    name: "onERC721Received",
    outputs: [
      {
        internalType: "bytes4",
        name: "",
        type: "bytes4",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
    ],
    name: "unlockToken",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x60803461008b57601f6103d738819003918201601f19168301916001600160401b0383118484101761009057808492604094855283398101031261008b576020610048826100a6565b916001600160a01b0391829161005e91016100a6565b169160018060a01b0319928360005416176000551690600154161760015560405161031c90816100bb8239f35b600080fd5b634e487b7160e01b600052604160045260246000fd5b51906001600160a01b038216820361008b5756fe608060408181526004918236101561001657600080fd5b600092833560e01c918263150b7a021461020d57508382636215be7714610172575081636aa00371146101495781637326afe0146100885750638da5cb5b1461005e57600080fd5b34610084578160031936011261008457905490516001600160a01b039091168152602090f35b5080fd5b905082346101465782600319360112610146576100a36102cb565b50546001600160a01b031633036100f6576020606492519162461bcd60e51b8352820152602060248201527f4f6e6c792076616c696461746f72732063616e20756e6c6f636b20746f6b656e6044820152fd5b6020608492519162461bcd60e51b8352820152602560248201527f4f6e6c7920746865206f776e65722063616e2063616c6c20746869732066756e60448201526431ba34b7b760d91b6064820152fd5b80fd5b50503461008457816003193601126100845760015490516001600160a01b039091168152602090f35b92915034610209576020366003190112610209576001546001600160a01b0316803b156102045783906064845180968193632142170760e11b83523387840152306024840152863560448401525af180156101fa576101cf578380f35b67ffffffffffffffff83116101e75750523880808380f35b634e487b7160e01b845260419052602483fd5b82513d86823e3d90fd5b505050fd5b5050fd5b939150346100845760803660031901126100845780356001600160a01b038116036100845761023a6102cb565b5060643567ffffffffffffffff8082116102c757366023830112156102c75781830135928184116102b457601f8401601f19908116603f01168701918211878310176102b45750845281855236602483830101116102b057906020948160248794018483013701015251630a85bd0160e11b8152f35b8280fd5b634e487b7160e01b855260419052602484fd5b8380fd5b602435906001600160a01b03821682036102e157565b600080fdfea2646970667358221220350594167fbc70462b6324599d1f1e51d8c33a9d50f56a7f55014b6db748256664736f6c63430008150033";

type NFTStorageERC721ConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: NFTStorageERC721ConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class NFTStorageERC721__factory extends ContractFactory {
  constructor(...args: NFTStorageERC721ConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    _collectionAddress: AddressLike,
    _owner: AddressLike,
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(
      _collectionAddress,
      _owner,
      overrides || {}
    );
  }
  override deploy(
    _collectionAddress: AddressLike,
    _owner: AddressLike,
    overrides?: NonPayableOverrides & { from?: string }
  ) {
    return super.deploy(_collectionAddress, _owner, overrides || {}) as Promise<
      NFTStorageERC721 & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): NFTStorageERC721__factory {
    return super.connect(runner) as NFTStorageERC721__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): NFTStorageERC721Interface {
    return new Interface(_abi) as NFTStorageERC721Interface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): NFTStorageERC721 {
    return new Contract(address, _abi, runner) as unknown as NFTStorageERC721;
  }
}
