/* Autogenerated file. Do not edit manually. */
/* eslint-disable */
export type { IERC1155Errors } from './IERC1155Errors';
export type { IERC20Errors } from './IERC20Errors';
export type { IERC721Errors } from './IERC721Errors';
