/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Bridge } from "./Bridge";
export type { BridgeStorage } from "./BridgeStorage";
export type { ERC1155Royalty } from "./ERC1155Royalty";
export type { ERC20Staking } from "./ERC20Staking";
export type { ERC20Token } from "./ERC20Token";
export type { ERC721Royalty } from "./ERC721Royalty";
export type { NftStorageERC1155 } from "./NftStorageERC1155";
export type { NftStorageERC721 } from "./NftStorageERC721";
