/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IHTSCompatibilityLayer,
  IHTSCompatibilityLayerInterface,
} from "../../../../../contracts/hedera/interfaces/IHTSCompatabilityLayer.sol/IHTSCompatibilityLayer";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "ownerOf",
    outputs: [
      {
        internalType: "address",
        name: "owner",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IHTSCompatibilityLayer__factory {
  static readonly abi = _abi;
  static createInterface(): IHTSCompatibilityLayerInterface {
    return new Interface(_abi) as IHTSCompatibilityLayerInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IHTSCompatibilityLayer {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IHTSCompatibilityLayer;
  }
}
